version: '3.9'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:4000
      - NEXT_PUBLIC_WS_URL=ws://backend:4000/live
    ports:
      - '3000:3000'
    depends_on:
      - backend
